sudo: required

language: generic

services:
  - docker

before_install:
  - docker-compose -f docker-compose.ci.yml up -d
  - docker-compose ps
  - docker ps -a

script:
  - docker-compose -f docker-compose.ci.yml exec truffle yarn run lint
  - docker-compose -f docker-compose.ci.yml exec truffle yarn run test:ci
